"""
Django settings for {{ project_name }} project.

Generated by 'django-admin startproject' using Django {{ django_version }}.

For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""

import os

from .base import (ALLOWED_HOSTS, AUTH_PASSWORD_VALIDATORS,  # noqa: F401
                   BASE_DIR, DATABASE_FILE_NAME, DATABASES, DJANGO_APPS,
                   LANGUAGE_CODE, MEDIA_ROOT, MEDIA_URL, MIDDLEWARE,
                   ROOT_URLCONF, SECRET_KEY, STATIC_DIR, STATIC_ROOT,
                   STATIC_URL, STATICFILES_DIRS, TEMPLATES, TEMPLATES_DIR,
                   TIME_ZONE, USE_I18N, USE_L10N, USE_TZ, WSGI_APPLICATION, )

# SECRET_KEY = get_secret('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

THIRD_PARTY_APPS = [
]

PRODUCTION_APPS = [
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PRODUCTION_APPS

# ------------------------------------------------------------------------------------
# 传入外部配置，如果有 Log 的配置，则应在此之后初始化 Log
try:
    with open(os.path.join(BASE_DIR, 'settings.conf'), encoding='utf-8') as f:
        exec(f.read())
except Exception:
    pass
